### ISSUE TITLE
Add RBAC

### ISSUE THREAD

**Issue by batazor** [micro-company/go-auth#24]
### 1. Every service add `RBAC` manifest

```
kind: Role
apiVersion: authorization/v1
metadata:
  namespace: micro-company
  name: go-mail
rules:
- resources: ["mail"]
  verbs: ["send", "status"]
- resources: ["metrics"]
  verbs: ["get"]
```

### 2. Generate RBAC-list

```
RBACList := [
  <ServiceName>: <RuleList>,
]
```

### 3. Generate UI-interface

UI-tree:

```
- <ServiceName>  
  - <ServiceResource 1> [ServiceVerbs]  
  - <ServiceResource 2> [ServiceVerbs]  
```

as example:

```
- go-mail-service
  - mail [x]send [ ]status
  - metrics [ ]get
```

### 4. Save rule for user or group
1. Write Role to DB
2. Check rule: `command -> checkJWT -> checkRBAC -> runCommand`
   1. For `checkJWT` and `checkRBAC` use Nginx plugins (from box nginx-ingress)

# Docs

1. [K8S RBAC docs](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)
1. [Kubernetes auth types](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/kubernetes/typed/rbac/v1)
2. [K8S auth types](https://github.com/kubernetes/api/blob/master/rbac/v1/types.go)

# Libs

1. [casbin](https://github.com/casbin/casbin)
